sudo: required

services:
  - docker

language: bash

env:
  global:
  - secure: "LY7vZmPO1OHy+RBAUmN1T1kasbGrfeqyfvAH5QpEgzu5GegYu7kvU1qlVXooQATmQ9+cC81OKbayRVYms9JaS9TQa06u9kDOdPCANc8SiFzT37FYhehfUVaT5uu2SBLmoKwnKu/QQTTTtsrAZCn5W1icAiLMaXbtCnWZlrW+zem1c3lm5SOQd2dZT3U03zOsFtnBqhQ7IgvCfP+0Q+WDt0W6gQave8DRsUU5tzZFWtX6z0BPqLbog9Mam5CbkuGEe+Jdi51kNXVwrFlqKxIZtL4KudtqyHMnGgp3lvefiKSmy8BQbOutpxcYo7Aa4sjej/r+spSvFw9mTZbX8D6WKsRosuTz0rSPIXBOmAteyS8t4uueVxhUBtmiU9V8pJ2V1SJQmE9V0+SWvYRoBdui697aIwR0Rb4r7vI5c+TpoA0FUPt2c902su5YDK96XIpdwqnDpxUkAC+vyEj33NJqpNzzeeicIpfiPCaootupwrCReUgzwq3sEzsn3yuZKbHM1svL1MtX/IbwjB76B+5RbaxZxjOnX8pJQsTo+VJ7a6zngI7kwldtUAzViKvkZ7FUQyNBAbN2kXh423OvivJgCcWy8bol6dtyBcMNR5zprWfRq2i0oRetE87UU344ArWC9injTxanPqQIYqBwhkiGHayDfaHpNIB+qlRyKi2o2BA="
  - secure: "emFVd4mZw4mXty7wp9VMfX+gOsrbKkNoyHMoWipVG2KZmhqlSDPiMHvneowUa/53eTFm7csOplv6npc/Fjd+dPackQZnytvdALw09au8DFI0j/1z1DRxC05YH+opedzU124tKY+oQUSSaHMk1pA/lj8hfVd/ibYQ8mqxUXXkWy4I1qwG3sMprU9esKSrw3KerVLyuF0CXe4BODYHUskmeVIx00XL8xlt17DXtR9SQvIRr7Mlsqg2CYAk65f37CuRigaQlJM4bD4bcjXevKxcBRBLNAnvg0dRdn6v//qMzcRFmpaA7JUFwLsCA2oze0blaqPqopev13ndzt+T12eVbwGmjSUU6AiYe2xvQp26UiTGFdgRn60N2Q8dtqK8xGtogXr8ZPKpNslh1t4NJJHgrPzvq2qU/eAlJOuITFuxfAVELQHRB7bR/wz2O+gnX9yX7Ayt0wlNmKgir/Whb/LdZaCXP7tguZ8AJ/VpextSAzfoP5bswOumPb/9/9gRio7bTByj+ruG+n5tqLLcFUoQmr00hP6NpkwvHY/6K2epYgRofxPEQQjj9u5CgMjMQVVrqZBO/3bm8MsWmh7/PaW+eCT8zmxZ/TuiwGc4Jszb7jAn0c/6ZcTWrpgYP7A992s7LRFY6KPD4OpEQ1n9pK5z6rXWY7t2J68wOsL9lktzi0A="
  - VERSION="$(cat .VERSION)"

before_install:
  - wget https://github.com/estesp/manifest-tool/releases/download/v0.7.0/manifest-tool-linux-amd64 -O manifest-tool
  - chmod +x manifest-tool
  - docker run --rm --privileged multiarch/qemu-user-static:register
  - echo "$DOCKER_PASS" | docker login -u "$DOCKER_LOGIN" --password-stdin

jobs:
  include:
    - stage: Build docker images
      env:
        - ARCH=amd64
      script:
      # Build amd64
        - docker build -t "duffbeer2000/dockertravis:$VERSION-$ARCH" ./amd64
      # Build amd64-full
        - docker build -t "duffbeer2000/dockertravis:full-$VERSION-$ARCH" ./amd64-full
      # Build amd64-min
        - docker build -t "duffbeer2000/dockertravis:min-$VERSION-$ARCH" ./amd64-min
      # Push Images to DockerHub

    - stage: Build docker images
      env:
        - ARCH=aarch64
      script:
      # Switch Architecture
        - docker run --rm --privileged multiarch/qemu-user-static:register --reset
      # Build aarch64
        - docker build -t "duffbeer2000/dockertravis:$VERSION-$ARCH" ./aarch64
      # Build aarch64-full
        - docker build -t "duffbeer2000/dockertravis:full-$VERSION-$ARCH" ./aarch64-full
      # Build aarch64-min
        - docker build -t "duffbeer2000/dockertravis:min-$VERSION-$ARCH" ./aarch64-min

    - stage: Build docker images
      env:
        - ARCH=arm7hf
      script:
      # Switch Architecture
        - docker run --rm --privileged multiarch/qemu-user-static:register --reset
      # Build armv7hf
        - docker build -t "duffbeer2000/dockertravis:$VERSION-$ARCH" ./armv7hf
      # Build armv7hf-full
        - docker build -t "duffbeer2000/dockertravis:full-$VERSION-$ARCH" ./armv7hf-full
      # Build armv7hf-min
        - docker build -t "duffbeer2000/dockertravis:min-$VERSION-$ARCH" ./armv7hf-min

after_success:
# Tag and push built images
  - >
    if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
      docker push duffbeer2000/dockertravis:$VERSION-$ARCH
      docker push duffbeer2000/dockertravis:full-$VERSION-$ARCH
      docker push duffbeer2000/dockertravis:min-$VERSION-$ARCH
    fi
    
publish:
# Update repository manifest for multiarch duffbeer2000/dockertravis:latest
  - >
    if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
      cat manifest.yml | sed "s/\$$VERSION/${VERSION}/g" > manifest.yaml
      #image: duffbeer2000/dockertravis:version
      cat manifest.yaml | sed "s/\$$FULLVERSION/${FULLVERSION}/g" > manifestversion.yaml
      #image: duffbeer2000/dockertravis:latest
      cat manifest.yaml | sed "s/\$$FULLVERSION/latest/g" > manifestlatest.yaml
      #image: duffbeer2000/dockertravis:min-version
      cat manifest.yml | sed "s/\$$VERSION/min-${VERSION}/g" > manifest.yaml
      cat manifest.yaml | sed "s/\$$FULLVERSION/min-${VERSION}/g" > manifestmin.yaml
      #image: duffbeer2000/dockertravis:full-version
      cat manifest.yml | sed "s/\$$VERSION/full-${VERSION}/g" > manifest.yaml
      cat manifest.yaml | sed "s/\$$FULLVERSION/full-${VERSION}/g" > manifestfull.yaml
      #Push to dockerhub
      mv manifestversion.yaml manifest.yaml
      ./manifest-tool --username $DOCKER_LOGIN --password $DOCKER_PASS push from-spec manifest.yaml
      mv manifestlatest.yaml manifest.yaml
      ./manifest-tool --username $DOCKER_LOGIN --password $DOCKER_PASS push from-spec manifest.yaml
      mv manifestmin.yaml manifest.yaml
      ./manifest-tool --username $DOCKER_LOGIN --password $DOCKER_PASS push from-spec manifest.yaml
      mv manifestfull.yaml manifest.yaml
      ./manifest-tool --username $DOCKER_LOGIN --password $DOCKER_PASS push from-spec manifest.yaml
    fi