sudo: required
services:
  - docker
language: bash
env:
  global:
  - secure: "LY7vZmPO1OHy+RBAUmN1T1kasbGrfeqyfvAH5QpEgzu5GegYu7kvU1qlVXooQATmQ9+cC81OKbayRVYms9JaS9TQa06u9kDOdPCANc8SiFzT37FYhehfUVaT5uu2SBLmoKwnKu/QQTTTtsrAZCn5W1icAiLMaXbtCnWZlrW+zem1c3lm5SOQd2dZT3U03zOsFtnBqhQ7IgvCfP+0Q+WDt0W6gQave8DRsUU5tzZFWtX6z0BPqLbog9Mam5CbkuGEe+Jdi51kNXVwrFlqKxIZtL4KudtqyHMnGgp3lvefiKSmy8BQbOutpxcYo7Aa4sjej/r+spSvFw9mTZbX8D6WKsRosuTz0rSPIXBOmAteyS8t4uueVxhUBtmiU9V8pJ2V1SJQmE9V0+SWvYRoBdui697aIwR0Rb4r7vI5c+TpoA0FUPt2c902su5YDK96XIpdwqnDpxUkAC+vyEj33NJqpNzzeeicIpfiPCaootupwrCReUgzwq3sEzsn3yuZKbHM1svL1MtX/IbwjB76B+5RbaxZxjOnX8pJQsTo+VJ7a6zngI7kwldtUAzViKvkZ7FUQyNBAbN2kXh423OvivJgCcWy8bol6dtyBcMNR5zprWfRq2i0oRetE87UU344ArWC9injTxanPqQIYqBwhkiGHayDfaHpNIB+qlRyKi2o2BA="
  - secure: "emFVd4mZw4mXty7wp9VMfX+gOsrbKkNoyHMoWipVG2KZmhqlSDPiMHvneowUa/53eTFm7csOplv6npc/Fjd+dPackQZnytvdALw09au8DFI0j/1z1DRxC05YH+opedzU124tKY+oQUSSaHMk1pA/lj8hfVd/ibYQ8mqxUXXkWy4I1qwG3sMprU9esKSrw3KerVLyuF0CXe4BODYHUskmeVIx00XL8xlt17DXtR9SQvIRr7Mlsqg2CYAk65f37CuRigaQlJM4bD4bcjXevKxcBRBLNAnvg0dRdn6v//qMzcRFmpaA7JUFwLsCA2oze0blaqPqopev13ndzt+T12eVbwGmjSUU6AiYe2xvQp26UiTGFdgRn60N2Q8dtqK8xGtogXr8ZPKpNslh1t4NJJHgrPzvq2qU/eAlJOuITFuxfAVELQHRB7bR/wz2O+gnX9yX7Ayt0wlNmKgir/Whb/LdZaCXP7tguZ8AJ/VpextSAzfoP5bswOumPb/9/9gRio7bTByj+ruG+n5tqLLcFUoQmr00hP6NpkwvHY/6K2epYgRofxPEQQjj9u5CgMjMQVVrqZBO/3bm8MsWmh7/PaW+eCT8zmxZ/TuiwGc4Jszb7jAn0c/6ZcTWrpgYP7A992s7LRFY6KPD4OpEQ1n9pK5z6rXWY7t2J68wOsL9lktzi0A="
install:
  - wget https://github.com/estesp/manifest-tool/releases/download/v0.7.0/manifest-tool-linux-amd64 -O manifest-tool
  - chmod +x manifest-tool
script:
# Build amd64
  - docker build -t "duffbeer2000/dockertravis:amd64" ./amd64
# Build amd64-min
  - docker build -t "duffbeer2000/dockertravis:amd64-min" ./amd64-min
# Build amd64-full
  - docker build -t "duffbeer2000/dockertravis:amd64-full" ./amd64-full
# Switch Architecture
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
# Build arm64v8
  - docker build -t "duffbeer2000/dockertravis:arm64v8" ./arm64v8
# Build arm64v8-min
  - docker build -t "duffbeer2000/dockertravis:arm64v8-min" ./arm64v8-min
# Build arm64v8-full
  - docker build -t "duffbeer2000/dockertravis:arm64v8-full" ./arm64v8-full
# Switch Architecture
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
# Build arm32v7
  - docker build -t "duffbeer2000/dockertravis:arm32v7" ./arm32v7
# Build arm32v7-min
  - docker build -t "duffbeer2000/dockertravis:arm32v7-min" ./arm32v7-min
# Build arm32v7-full
  - docker build -t "duffbeer2000/dockertravis:arm32v7-full" ./arm32v7-full
# Switch Architecture
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
# Build arm32v6
  - docker build -t "duffbeer2000/dockertravis:arm32v6" ./arm32v6
# Build arm32v6-min
  - docker build -t "duffbeer2000/dockertravis:arm32v6-min" ./arm32v6-min
# Build arm32v6-full
  - docker build -t "duffbeer2000/dockertravis:arm32v6-full" ./arm32v6-full
# Switch Architecture
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
# Build arm32v5
  - docker build -t "duffbeer2000/dockertravis:arm32v5" ./arm32v5
# Build arm32v5-min
  - docker build -t "duffbeer2000/dockertravis:arm32v5-min" ./arm32v5-min
# Build arm32v5-full
  - docker build -t "duffbeer2000/dockertravis:arm32v5-full" ./arm32v5-full
#
after_success:
# Tag and push built images
  - >
    if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
      docker login -u="$DOCKER_LOGIN" -p="$DOCKER_PASS"
      VERSION=$(cat .VERSION)
      docker tag duffbeer2000/dockertravis:amd64 duffbeer2000/dockertravis:amd64-$VERSION
      docker push duffbeer2000/dockertravis:amd64
      docker push duffbeer2000/dockertravis:amd64-$VERSION
      docker tag duffbeer2000/dockertravis:amd64-min duffbeer2000/dockertravis:amd64-min-$VERSION
      docker push duffbeer2000/dockertravis:amd64-min
      docker push duffbeer2000/dockertravis:amd64-min-$VERSION
      docker tag duffbeer2000/dockertravis:amd64-full duffbeer2000/dockertravis:amd64-full-$VERSION
      docker push duffbeer2000/dockertravis:amd64-full
      docker push duffbeer2000/dockertravis:amd64-full-$VERSION
      docker tag duffbeer2000/dockertravis:arm64v8 duffbeer2000/dockertravis:arm64v8-$VERSION
      docker push duffbeer2000/dockertravis:arm64v8
      docker push duffbeer2000/dockertravis:arm64v8-$VERSION
      docker tag duffbeer2000/dockertravis:arm64v8-min duffbeer2000/dockertravis:arm64v8-min-$VERSION
      docker push duffbeer2000/dockertravis:arm64v8-min
      docker push duffbeer2000/dockertravis:arm64v8-min-$VERSION
      docker tag duffbeer2000/dockertravis:arm64v8-full duffbeer2000/dockertravis:arm64v8-full-$VERSION
      docker push duffbeer2000/dockertravis:arm64v8-full
      docker push duffbeer2000/dockertravis:arm64v8-full-$VERSION
      docker tag duffbeer2000/dockertravis:arm32v7 duffbeer2000/dockertravis:arm32v7-$VERSION
      docker push duffbeer2000/dockertravis:arm32v7
      docker push duffbeer2000/dockertravis:arm32v7-$VERSION
      docker tag duffbeer2000/dockertravis:arm32v7-min duffbeer2000/dockertravis:arm32v7-min-$VERSION
      docker push duffbeer2000/dockertravis:arm32v7-min
      docker push duffbeer2000/dockertravis:arm32v7-min-$VERSION
      docker tag duffbeer2000/dockertravis:arm32v7-full duffbeer2000/dockertravis:arm32v7-full-$VERSION
      docker push duffbeer2000/dockertravis:arm32v7-full
      docker push duffbeer2000/dockertravis:arm32v7-full-$VERSION
      docker tag duffbeer2000/dockertravis:arm32v6 duffbeer2000/dockertravis:arm32v6-$VERSION
      docker push duffbeer2000/dockertravis:arm32v6
      docker push duffbeer2000/dockertravis:arm32v6-$VERSION
      docker tag duffbeer2000/dockertravis:arm32v6-min duffbeer2000/dockertravis:arm32v6-min-$VERSION
      docker push duffbeer2000/dockertravis:arm32v6-min
      docker push duffbeer2000/dockertravis:arm32v6-min-$VERSION
      docker tag duffbeer2000/dockertravis:arm32v6-full duffbeer2000/dockertravis:arm32v6-full-$VERSION
      docker push duffbeer2000/dockertravis:arm32v6-full
      docker push duffbeer2000/dockertravis:arm32v6-full-$VERSION
      docker tag duffbeer2000/dockertravis:arm32v5 duffbeer2000/dockertravis:arm32v5-$VERSION
      docker push duffbeer2000/dockertravis:arm32v5
      docker push duffbeer2000/dockertravis:arm32v5-$VERSION
      docker tag duffbeer2000/dockertravis:arm32v5-min duffbeer2000/dockertravis:arm32v5-min-$VERSION
      docker push duffbeer2000/dockertravis:arm32v5-min
      docker push duffbeer2000/dockertravis:arm32v5-min-$VERSION
      docker tag duffbeer2000/dockertravis:arm32v5-full duffbeer2000/dockertravis:arm32v5-full-$VERSION
      docker push duffbeer2000/dockertravis:arm32v5-full
      docker push duffbeer2000/dockertravis:arm32v5-full-$VERSION
    fi
# Update repository manifest for multiarch duffbeer2000/dockertravis:latest
  - >
    if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
      ./manifest-tool --username $DOCKER_LOGIN --password $DOCKER_PASS push from-spec manifest.yml
    fi
