sudo: required
services:
  - docker
language: bash
env:
  global:
    secure: "Ny5fEPffjGdQGngfhImeLXtTRRo6TAfnyWojg9HzY7ZjpsMVLAEHEyukEIottOBsPH2O/pOim0re/zZibkhW7Pxa0dfvS2idQk8syLL3II7E4nrvhtGNmeywBynEpuPg0Dlc/lxgWqq3ROtp5KeXNFFfhgYgEhbu2mJSnrrOKotp+tMdyYRdoZcr35J03AK2Q4nqt1AgZD2iXsOETp12A0AutzT6ug0mq2Y7sZ0Uu2/h4UF9ccnBzPvS1jw2/GHG+a4VZ+CRMbm+3HRdwAXFqHG09hdmTslgNkRUngCkdTFFc2QEfFuG34p7HUccPFf6GauIP0lFbXV0PRPZ8/gQ6ajiLLl8GwT3nT/L2MYQJ4zVcb0j+8uhN9nMcvOxbrRj0b5btp759R+5MZJvSSwqgCZKZXu8md+Ff4mc6z/5a2cgHMEm020VMToL5RJH2bL1DIjXjNKzPtsinF7c0ZHJSXC9/zNlw5zU81NST53VHgySMeL9LIwd6MVzjbgaKAQV2Kn/kFkgs/go7L9tMUoTKhDVObZ9N1NO3RgDKu/uOcLPMZSyZF6fPADNbQTOZCiC8+PZ4b5RkwlBuMpyitxTV89eba4MjmjiatNSQtGuBVAZQ5ADu0REDxM3jYx6Pv90s/ZXvOhrRvDSuT2oV6twBYWqJ0WFGPlgu4/xCMtxbqY="
    secure: "OETIINeoqmQGz9jfpYoN/jVn4ARoaxfPVja57zaS4o2pvH1cl9Usl8+V2MOrr18l8ASAjAFmG0OJ1HnFs9fjM2GBMjYEMb+3e/2WWPlub7zpWIAAKkkXVoVWW3+iIPdARGL+dHL5Fmp0HD3FqnQ+R62XVvweKrJZhdzJDEUV86ljZKDayLWEha5WadhPqhN+XiQhsio9oLkjgJ613w8M3yYqzcjD3D3tVV1zPvsG0NoQcOTKqrfeYFO7OLXBBYRYXO3wNRBalUsaOFqE6YPsOiuSYyQXqgnl17B7jSXrwdPt3yNRt1Q1nOayVRkCMt5ezKV+AlCoiMrh8VxBi9pDIGvYKFC3EmfTb/Kaf92khTk5ZDoP9h/NjY4JvwoReNrHndbtfOW2klyd5LAeOLoH0Kj2XwPtGfpAQsfTJ3jwB7SuvKUuKmAbFVGN8MWjWK8scRd6KmgxAmti7GJI7e4o51RjLZHk8lBoXcqyVK/28UxlhnpXi9+7BJPshBxVaHEoGaJpg6oSMBwNzl06u4/SZ1rBy9si9hxStiT1c/8XDGZsHoE+XF6zKwB1jVyuDxCKaKmZ9wEJCyitQxI42Ya8L2y/Iopsh3B8tGR3Hrm0W0TbqX6Rf1UgP7BF+92EAp+H94ArDf23sMVvxNebAWO6srSbPb6h9nMDv9jm1/kSYqo="
  install:
  - wget https://github.com/estesp/manifest-tool/releases/download/v0.7.0/manifest-tool-linux-amd64 -O manifest-tool
  - chmod +x manifest-tool
script:
# Build amd64
  - docker build -t "duffbeer2000/iobroker:amd64" ./amd64
# Build amd64-min
  - docker build -t "duffbeer2000/iobroker:amd64-min" ./amd64-min
# Build amd64-full
  - docker build -t "duffbeer2000/iobroker:amd64-full" ./amd64-full
# Build armhf
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
  - docker build -t "duffbeer2000/iobroker:armhf" ./armhf
# Build armhf-min
  - docker build -t "duffbeer2000/iobroker:armhf-min" ./armhf-min
# Build armhf-full
  - docker build -t "duffbeer2000/iobroker:armhf-full" ./armhf-full
#
after_success:
# Tag and push built images
  - >
    if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
      docker login -u="$DOCKER_LOGIN" -p="$DOCKER_PASS"
      VERSION=$(cat .VERSION)
      docker tag duffbeer2000/iobroker:amd64 duffbeer2000/iobroker:amd64-$VERSION
      docker push duffbeer2000/iobroker:amd64
      docker push duffbeer2000/iobroker:amd64-$VERSION
      docker tag duffbeer2000/iobroker:amd64-min duffbeer2000/iobroker:amd64-min-$VERSION
      docker push duffbeer2000/iobroker:amd64-min
      docker push duffbeer2000/iobroker:amd64-min-$VERSION
      docker tag duffbeer2000/iobroker:amd64-full duffbeer2000/iobroker:amd64-full-$VERSION
      docker push duffbeer2000/iobroker:amd64-full
      docker push duffbeer2000/iobroker:amd64-full-$VERSION
      docker tag duffbeer2000/iobroker:armhf duffbeer2000/iobroker:armhf-$VERSION
      docker push duffbeer2000/iobroker:armhf
      docker push duffbeer2000/iobroker:armhf-$VERSION
      docker tag duffbeer2000/iobroker:armhf-min duffbeer2000/iobroker:armhf-min-$VERSION
      docker push duffbeer2000/iobroker:armhf-min
      docker push duffbeer2000/iobroker:armhf-min-$VERSION
      docker tag duffbeer2000/iobroker:armhf-full duffbeer2000/iobroker:armhf-full-$VERSION
      docker push duffbeer2000/iobroker:armhf-full
      docker push duffbeer2000/iobroker:armhf-full-$VERSION
    fi
# Update repository manifest for multiarch duffbeer2000/iobroker:latest
  - >
    if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
      ./manifest-tool --username $DOCKER_LOGIN --password $DOCKER_PASS push from-spec manifest.yml
    fi
